import '../models/babysitter_profile.dart';

/// Static/mock babysitter data for demonstration when database is empty.
class StaticBabysitterData {
  /// Get a list of mock babysitter profiles.
  static List<BabysitterProfile> getMockBabysitters() {
    return [
      BabysitterProfile(
        id: 'static_1',
        name: 'Sarah Johnson',
        experience: '5 years of professional childcare experience',
        skills: 'CPR Certified, First Aid, Child Development',
        pricePerHour: '25',
        availability: 'Weekdays 9am-6pm, Weekends available',
        ratingAverage: 4.8,
        ratingCount: 24,
        backgroundVerified: true,
        isAvailableNow: true,
      ),
      BabysitterProfile(
        id: 'static_2',
        name: 'Emily Martinez',
        experience: '3 years babysitting, Early Childhood Education degree',
        skills: 'CPR, First Aid, Special Needs Care',
        pricePerHour: '22',
        availability: 'Evenings and weekends',
        ratingAverage: 4.9,
        ratingCount: 18,
        backgroundVerified: true,
        isAvailableNow: false,
      ),
      BabysitterProfile(
        id: 'static_3',
        name: 'Jessica Chen',
        experience: '7 years experience with infants and toddlers',
        skills: 'Infant Care Specialist, CPR, Nutrition',
        pricePerHour: '28',
        availability: 'Monday-Friday, flexible hours',
        ratingAverage: 4.7,
        ratingCount: 31,
        backgroundVerified: true,
        isAvailableNow: true,
      ),
      BabysitterProfile(
        id: 'static_4',
        name: 'Amanda Williams',
        experience: '4 years, Former preschool teacher',
        skills: 'Early Learning Activities, Art & Crafts, Music',
        pricePerHour: '24',
        availability: 'Afternoons and weekends',
        ratingAverage: 4.6,
        ratingCount: 15,
        backgroundVerified: false,
        isAvailableNow: true,
      ),
      BabysitterProfile(
        id: 'static_5',
        name: 'Maria Rodriguez',
        experience: '6 years, Bilingual (English/Spanish)',
        skills: 'CPR, First Aid, Language Development',
        pricePerHour: '26',
        availability: 'Full-time availability',
        ratingAverage: 4.9,
        ratingCount: 42,
        backgroundVerified: true,
        isAvailableNow: false,
      ),
      BabysitterProfile(
        id: 'static_6',
        name: 'Rachel Thompson',
        experience: '2 years, Nursing student',
        skills: 'Medical Training, CPR, First Aid Certified',
        pricePerHour: '20',
        availability: 'Evenings and weekends',
        ratingAverage: 4.5,
        ratingCount: 12,
        backgroundVerified: true,
        isAvailableNow: true,
      ),
      BabysitterProfile(
        id: 'static_7',
        name: 'Lisa Anderson',
        experience: '8 years, Mother of 3',
        skills: 'Multi-child care, Homework help, Meal prep',
        pricePerHour: '30',
        availability: 'After school and weekends',
        ratingAverage: 5.0,
        ratingCount: 28,
        backgroundVerified: true,
        isAvailableNow: true,
      ),
      BabysitterProfile(
        id: 'static_8',
        name: 'Nicole Brown',
        experience: '3 years, Child Psychology major',
        skills: 'Behavioral Management, Educational Activities',
        pricePerHour: '23',
        availability: 'Flexible schedule',
        ratingAverage: 4.4,
        ratingCount: 9,
        backgroundVerified: false,
        isAvailableNow: false,
      ),
    ];
  }
}
